### ISSUE TITLE
Wrong adapter specified for R2.

### ISSUE THREAD

**Issue by nh13** [hsulab-arc/SystematicDiscoveryRecombinases2022#3]
The [R2 adapter used](https://github.com/hsulab-arc/SystematicDiscoveryRecombinases2022/blob/2643ef03f1828a2ef6e93c10e8e81e61e3c79c23/integration-mapping-pipeline/snakemake/Snakefile#LL82C8-L82C149) is `AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT`, which is the TruSeq DNA sequence adapter for R1 (thus you search for it on R2).
Running `fastp` on the raw `SRR21306552` FASTQs does not show this adapter being trimmed from R2, but instead something else:
![fastp R2](https://user-images.githubusercontent.com/846274/228086241-53cbc38f-e5d8-4198-8e36-227c4aa4871c.png)

From Supplementary Figure 2H, the P5 adapter is added via tagmentation:
<img width="309" alt="supp fig 2h" src="https://user-images.githubusercontent.com/846274/228085853-881e56bc-743f-469f-8fa3-3e353d7c2689.png">.  
This presumably using the Nextera Transpose Adapters, which for read 1 is `TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG` (see page 3 [here](https://dnatech.genomecenter.ucdavis.edu/wp-content/uploads/2019/03/illumina-adapter-sequences-2019-1000000002694-10.pdf)).  The reverse complement is `CTGTCTCTTATACACATCTGACGCTGCCGACGA`.  The adapters found above for R2 are exactly this.

**Comment by nh13** [comment]
Note: I don't think this should affect the results since `--detect_adapter_for_pe` was used with `fastp` so the adapters are likely trimmed, but I do get different results when explicitly specifying the R2 adapter and removing `--detect_adapter_for_pe`.

**Comment by durrantmm** [comment]
Thank you for pointing this out!
