### ISSUE TITLE
i7 incorrect in paper supplement, with no identification which samples have use which i7

### ISSUE THREAD

**Issue by nh13** [hsulab-arc/SystematicDiscoveryRecombinases2022#6]
1. The i7 sequences look to be truncated a single base.  For example, the nested inner donor primer listed for the LP i7 primers is `CAGCGAGTCAGTGAGCGAG` in `41587_2022_1494_MOESM8_ESM.xlsx`, but on SRA (e.g. [`SRR21306552`](https://www.ncbi.nlm.nih.gov/sra/?term=SRR21306552)) there is an extra G.  I believe the SRA is correct, could you confirm?
![Screen Shot 2023-03-27 at 4 16 45 PM](https://user-images.githubusercontent.com/846274/228087920-be6b8326-faf4-4e76-bdb3-feb9a2bc46d3.png)
2. In the supplementary materials `41587_2022_1494_MOESM8_ESM.xlsx`, the sequences for the pseodosite and LP i7 primer are given, but it is not identified which samples contain which i7 primers.  I think the SRA is correct, could you confirm?

**Comment by durrantmm** [comment]
Yes, I can confirm that the correct primer is `CAGCGAGTCAGTGAGCGAGG`, thank you for bringing this to our attention.
