### ISSUE TITLE
Alignment to human may miss alignments

### ISSUE THREAD

**Issue by nh13** [hsulab-arc/SystematicDiscoveryRecombinases2022#7]
Consider adding `-T 20` to your `bwa mem` commands for more sensitive mapping due to some samples having short reads, especially after "cleaning".

When [aligning to the human genome](https://github.com/hsulab-arc/SystematicDiscoveryRecombinases2022/blob/2643ef03f1828a2ef6e93c10e8e81e61e3c79c23/integration-mapping-pipeline/snakemake/Snakefile#L230) using both R1 and R2, some reads may fail to align due to aligned bases being too short.

For example, many samples are run with 2x74bp. 
After trimming off the leading inner donor primer from R2 (20bp) even with no stagger, we are left with 50bp. 
Next, the integrase sequence after that primer is on the order of 30bp before it hits the crossover to the genome, that leaves only 20bp left that needs to map to the genome!

Next, `bwa mem` by default requires an alignment score of 30, which is 30 perfect matches (see the `-T` option).
So the above reads will not align the R2 to the genome unless `-T` is explicitly set.

Some samples even have UMI that reduce this even further!

**Comment by durrantmm** [comment]
Thank you for suggesting this sensitivity improvement!
