### ISSUE TITLE
Off-target sites align to full length attP, so may not be chimeras instead?

### ISSUE THREAD

**Issue by nh13** [hsulab-arc/SystematicDiscoveryRecombinases2022#8]
I am trying to understand why in the paper, the following integration site was reported (`chr17:70004850-70004852(-)`) in the supplementary material `41587_2022_1494_MOESM5_ESM.xlsx`, with one observed read.

I believe the read pair has the following name in the FASTQ: `SRR21306552.5260005`.  Can you confirm?

I mapped these reads to the human genome (hg38) with the full length attP (for BxbI in `41587_2022_1494_MOESM4_ESM.xlsx`) contig appended (the full length donor was never given in the paper, so I can't check against attD, just attP, see #5).

R1 maps the genome with cigar `58M16S` at the site you reported, while R2 (after removing the leading stagger and inner-donor-primer) maps to attP sequence with `42M12S`.  Reverse complementing R1 so we have R1 and R2 on the same strand, then aligning the 16bp of soft-clipping from R1 to attP, we get the following:

```
R1: 16S58M:                                                  TACGGTACAAACCCAGCCGCCACCATGCCTGGCTAATTTTTCATACTTTTAATAGAGATGGGGTTTCACCATAT
Full attP:              GTGGTTTGTCTGGTCAACCACCGCGGTCTCAGTGGTGTACGGTACAAACCCA
R2: 42M12S: AAGCGGAAGAGCGTGGTTTGTCTGGTCAACCACCGCGGTCTCAGTGGTGTACGG
```

Clearly we have a full length attP followed by the human genome, whereas I would have expected R2 to only align left-side of attP, namely `P`, and perhaps including the `GT` overhang, which is `GTGGTTTGTCTGGTCAACCACCGCGGT`.  But clearly R2 does not sequence across the crossover into the human genome (the reads are too short), and using R1, we can see we don't have the recombination pattern we'd expect (attL/attR).

I found similar issues both with other off-target sites, both to full length attP sequences as well as some that read beyond the expected crossover point in the attP by up to 15bp (e.g. aligned the first 45bp of attP above, then human genome).

I am inclined to not believe these are off-target sites, and perhaps could be a (PCR?) chimera?   I think this is may also be exacerbated by the short reads and the need to be more sensitive in alignment (see #7).  Thoughts?

**Comment by durrantmm** [comment]
Hi Nils, yes that looks correct, most likely a chimera. This seems to be an edge case that made it through the filters. We were trying to find a balance between being too conservative and too permissive in what we let through and what we reported. We did not intend to imply that Bxb1 had many off-targets. As you can see in Supplementary Figure 2, we indicated that none of the 6 potential off-targets detected for Bxb1 were found to replicate. Thank you for pointing this out.

**Comment by durrantmm** [comment]
It's possible that other reads that do have proper break points are also spurious or chimeras, which is why it's important to focus on how they replicate across samples.
